# notes on jupyter and numpy

In [1]:
import numpy as np

np allows for arrays of a defined type, unlike python's lists which can hold various data types

In [3]:
array = np.zeros(12)

In [4]:
array

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [5]:
array2 = np.full(5, 1.1)

In [6]:
array2

array([1.1, 1.1, 1.1, 1.1, 1.1])

In [7]:
array3 = np.arange(3,9)

In [8]:
array3

array([3, 4, 5, 6, 7, 8])

In [9]:
array4 = np.linspace(1, 10)

In [10]:
np.linspace? #run a question mark to get documentation

In [11]:
array.shape

(12,)

In [12]:
array.nbytes

96

In [13]:
array.dtype

dtype('float64')

In [14]:
identity = np.identity(5)

In [15]:
identity

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [16]:
array2d = np.zeros((5,5))

In [17]:
array2d

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [18]:
list_to_np = np.array([1,2,3])

In [19]:
list_to_np

array([1, 2, 3])

In [20]:
list_to_np2 = np.array([[1,2,3],[4,5,6]])

In [21]:
list_to_np2

array([[1, 2, 3],
       [4, 5, 6]])

In [22]:
sum2 = array2.sum()

In [23]:
sum2

5.5

In [24]:
min2 = array4.min()

In [25]:
min2

1.0

In [27]:
copy = array2.copy()

In [28]:
copy

array([1.1, 1.1, 1.1, 1.1, 1.1])