# Today's topic is random!

In [4]:
import numpy as np

In [12]:
randomA = np.random.rand(5,2)
randomA

array([[0.54254437, 0.14217005],
       [0.37334076, 0.67413362],
       [0.44183317, 0.43401399],
       [0.61776698, 0.51313824],
       [0.65039718, 0.60103895]])

In [9]:
np.random.seed(10)

In [10]:
random_seed_A = np.random.rand(5,2) # running this after setting a seed produces the "same random" numbers
random_seed_A

array([[0.77132064, 0.02075195],
       [0.63364823, 0.74880388],
       [0.49850701, 0.22479665],
       [0.19806286, 0.76053071],
       [0.16911084, 0.08833981]])

In [13]:
random_neg_A = np.random.randn(10) # random numbers include negative numbers
random_neg_A

array([ 0.09914922,  1.39799638, -0.27124799,  0.61320418, -0.26731719,
       -0.54930901,  0.1327083 , -0.47614201,  1.30847308,  0.19501328])

In [17]:
random_ints_A = np.random.randint(low=1,high=5,size=(2,2)) 
random_ints_A

array([[4, 1],
       [1, 3]])

### Now for some linear algebra!

Dot product?

In [22]:
matrix_1 = np.random.randint(low=0,high=100,size=(1,3)) 
matrix_2 = np.random.randint(low=0,high=100,size=(3,1)) 

matrix_1

array([[96, 62, 57]])

In [23]:
matrix_2

array([[79],
       [42],
       [57]])

In [25]:
dot_product = matrix_1.dot(matrix_2)
dot_product

array([[13437]])